"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-736d-3)=rke4*_%8#+8$bn%1kp=^x(m@whremzf--o_@1alein'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',                 # enables Cross-Origin Resource Sharing for frontend calls
    'rest_framework',              # Django REST Framework for building JSON APIs
    'api',                          # our local app housing all API code
    'accounts',                     # our auth endpoints app
    'profiles',
]

# settings.py — MIDDLEWARE
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',        # security headers and protections
    'corsheaders.middleware.CorsMiddleware',                # handle CORS early so responses get CORS headers
    'django.contrib.sessions.middleware.SessionMiddleware', # manage server-side sessions (must be before Common)
    'django.middleware.common.CommonMiddleware',            # common utilities (ETags, URL rewriting, etc.)
    'django.middleware.csrf.CsrfViewMiddleware',            # protect against CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware', # attach user/auth to request
    'django.contrib.messages.middleware.MessageMiddleware', # one-off notification messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # X-Frame-Options header
]


# Allow our React dev servers to talk to Django during development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",       # Create React App default dev URL
    "http://127.0.0.1:3000",       # loopback variant for CRA
    "http://localhost:5173",       # Vite default dev URL
    "http://127.0.0.1:5173",       # loopback variant for Vite
]

# Trust those origins for CSRF as well (Django form posts, session auth, etc.)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",       # trust CRA origin for CSRF
    "http://127.0.0.1:3000",       # loopback variant
    "http://localhost:5173",       # trust Vite origin
    "http://127.0.0.1:5173",       # loopback variant
]

# REST Framework global settings placeholder
REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': [...],  # we’ll set auth later
    # 'DEFAULT_PERMISSION_CLASSES':    [...],  # and perms later
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py — DRF + JWT + CORS config (order here is flexible; bottom is fine)
from datetime import timedelta                             # used to set token lifetimes

REST_FRAMEWORK = {                                         # DRF global settings
    'DEFAULT_AUTHENTICATION_CLASSES': (                    # list of auth backends
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # use JWT for API auth
    ),
}

SIMPLE_JWT = {                                             # SimpleJWT behavior
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),        # short-lived access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),           # longer-lived refresh token
}

CORS_ALLOW_ALL_ORIGINS = True                              # allow all origins in dev (tighten later)
# CORS_ALLOWED_ORIGINS = [                                 # prefer this in prod with explicit origins
#     'http://localhost:3000',                             # frontend dev server
# ]

